name: Check links
description: Check all hyperlinks in the given Markdown file
author: nprimo
inputs:
  filepath:
    description: "The file path of the Markdown file to be checked"
    required: true
  # TODO: implement expections? How should I pass a list of string or regex?
  #exceptions:
    #description: "List of patterns that, if contained in the links, should skip the check"
    #required: false
runs:
  using: docker
  image: ghcr.io/01-edu/check-links:latest
